### ISSUE TITLE
Please stop putting folders into ServerStorage

### ISSUE THREAD

**Issue by Kampfkarren** [tiffany352/Roblox-Tag-Editor#5]
My ServerStorage is important to me. I hate using Tag Editor because it keeps putting mysterious unnamed folders into my ServerStorage that I delete and then lose functionality of Tag Editor for. Find some hidden service to put them in, I don't want to see it.

**Comment by Kampfkarren** [comment]
Reading the code, maybe it's a glitch that my Tag Editor only names the folders Folder. I don't know. Either way, I don't want it.

**Comment by tiffany352** [comment]
The only folders that the tag editor creates should be these:

- TagList
- TagGroupList

It only creates these folders when you create state that needs to be saved. It will not randomly create an empty tags folder like some other plugins.

There is nowhere else to put them. I originally tried to put them into CollectionService, but that service does not replicate in Team Create.

Are you seeing folders other than these two? If so, then I need a way to repro the issue so I can fix it.

**Comment by Kampfkarren** [comment]
There are hidden servers that replicated on Team Create, JointsService is I believe one of them.

I'm not seeing TagList *or* TagGroupList. I'm seeing "Folder". Maybe I'm using a different/outdated plugin?

Is there a link to your build?

**Comment by tiffany352** [comment]
The official, latest version of the plugin is available from the website from here: https://www.roblox.com/library/948084095/Tag-Editor
Make sure that you do not have any version that was created by a user named "PluginCreator" or you've been compromised by malicious code. Also check if you have any locally installed plugins (click the "Plugins Folder" button in the plugins tab), and if there are local copies of the tag editor, remove them.

JointsService is extremely ugly because it only allows joints to be parented to it, so I would have to put the tags inside a joint inside JointsService.

There are others, such as HttpService and MarketplaceService, but these are about to be changed so that they don't replicate anymore. Right now there really is no good place for plugins to store this sort of data. I also think it'd be really awful to store the tag list in MarketplaceService on a conceptual level. It's arguably worse than when games used to store stuff in Lighting.

**Comment by Kampfkarren** [comment]
I had the correct plugin, but on an outdated version. It's unfortunate to hear they're changing the system without giving plugin developers an alternative. I'm closing this but I still hate that this is in my ServerStorage.
